

export interface builderFieldCompInterface{
  code:string,
  name:string,
  type:string,
  flexiLabel:string,
  label:string,
  hideLabel:boolean,
  labelPosition:string,
  labelWidth:number,
  labelMargin:number,
  width:string,
  placeholder:string,
  description:string,
  tooltip:string,
  errorLabel:string,
  inputMask:string,
  prefix:string,
  suffix:string,
  customCssClass:string,
  tabIndex:string,
  clearValue:boolean,
  hidden:boolean,
  disabled:boolean,
  defaultValue:string,
  sqlQuery:string,
  jsFunction:string,
  jsonLogic:string,
  nonPersistent:string,
  autoComplete:string,
  appliedValidation:string,
  minimumLength:number,
  maximumLength:number,
  regularExpression:string,
  customErrorFunction:string,
  customValidationFunction:string,
  JSONLogic:string,
  marginTop:string,
  marginRight:string,
  marginBottom:string,
  marginLeft:string,
  customFunction:string,
  conditionalJsonLogic:string,



}
